Adding Clickhouse Playground example
ibis-project/ibis-examples pull request #11
Opened 2023-04-12 16:25 UTC by marlenezw

This is an initial PR to solve [issue 2](https://github.com/ibis-project/ibis-examples/issues/2). This PR adds an example of connecting to a table through Clickhouse Playground and doing some basic analytics.

2023-04-12 16:26 UTC, marlenezw commented
@jcrist here's the initial draft PR. Are there specific things you'd like me to show with the dataset? Happy to improve this in the morning

2023-04-12 18:05 UTC, danepitkin commented
Nice! Shall we remove the `.DS_Store` files?

2023-04-12 18:06 UTC, jcrist commented
yeah, I just added those to the `.gitignore` to prevent that happening in the future.

2023-04-13 10:28 UTC, marlenezw commented
Just noticed that. I just used `git add .` I'll remove them!

2023-04-14 14:37 UTC, gforsyth requested changes
Thanks for putting this together @marlenezw!

One small nit in a link, and those pesky `.DS_Store` files are still here.

Also, we don't currently have a policy, but I think we should probably run `black` over all the notebooks so that the code is formatted consistently between examples.

2023-04-14 14:37 UTC, gforsyth commented on examples/clickhouse_hackernews_example.ipynb
> +    "For more information on using Ibis with Clickhouse check out the docs page here: https://ibis-project.org/backends/ClickHouse/?h=click#clickhouse"
```suggestion
    "For more information on using Ibis with Clickhouse check out the docs page here: https://ibis-project.org/backends/ClickHouse/"
```

removing the highlighting of `Click` on the linked page

2023-04-14 14:41 UTC, jcrist commented
>  but I think we should probably run black over all the notebooks so that the code is formatted consistently between examples.

Good idea Gil! I can push up a hook for the formatting changes with black. TIL black supports notebooks.

2023-04-14 21:28 UTC, jcrist commented
Thanks Marlene! I've made a few changes to finish up this notebook. Merging!

2023-04-14 21:28 UTC, merged

2023-06-27 09:31 UTC, marlenezw commented
Ah, sorry for the silence on this. Just catching up with Github notifications 😅  Thank you!!!